CREATE TABLE IF NOT EXISTS `all_fans`(userID int NOT NULL AUTO_INCREMENT,PRIMARY KEY(userID),username varchar(50),full_name varchar(900),time varchar(50),date varchar(50),password varchar(50),email varchar(100),phone_no varchar(50),state varchar(50),pass_hint varchar(200),sex varchar(50), ip varchar(50),profilepic varchar(200),thumbprofilepic varchar(200),privacy varchar(100),remember_login varchar(5),hashed_username varchar(300),`lls` varchar(300),`a_t` varchar(40));
CREATE TABLE IF NOT EXISTS `all_artiste`(userID int NOT NULL AUTO_INCREMENT,PRIMARY KEY(userID),username varchar(50),full_name varchar(900),time varchar(50),date varchar(50),password varchar(50),email varchar(100),phone_no varchar(50),state varchar(50),pass_hint varchar(200),sex varchar(50), ip varchar(50),profilepic varchar(200),thumbprofilepic varchar(200),privacy varchar(100),remember_login varchar(5),hashed_username varchar(300),`lls` varchar(300),`a_t` varchar(40));
CREATE TABLE IF NOT EXISTS `check_refresh_time`(refreshID int NOT NULL AUTO_INCREMENT,PRIMARY KEY(refreshID),username varchar(50),time varchar(50),time2 varchar(50),group_codename varchar(200));
CREATE TABLE IF NOT EXISTS `post_comments`(commentID int NOT NULL AUTO_INCREMENT,PRIMARY KEY(commentID),comment_content text(10000),comment_by varchar(100),time varchar(50),date varchar(50),time2 varchar(50),dp_of_users varchar(500),fullname varchar(500),post_id varchar(500));
CREATE TABLE IF NOT EXISTS `new_msg`(msgID int NOT NULL AUTO_INCREMENT,PRIMARY KEY(msgID),msg_content text(10000),msg_rcver varchar(100),msg_sender varchar(100),msg_sender_fn varchar(100),dp_of_sender varchar(500),time varchar(50),date varchar(50),time2 varchar(50),seen_msg varchar(50),msg_id varchar(500),msg_key text(5000));
CREATE TABLE IF NOT EXISTS `like_post`(ID int NOT NULL AUTO_INCREMENT,PRIMARY KEY(ID),people varchar(200),post_id varchar(500),fullname varchar(500),dp varchar(500));
CREATE TABLE IF NOT EXISTS `public_gallery`(photoID int NOT NULL AUTO_INCREMENT,PRIMARY KEY(photoID),photo_name varchar(200),upload_by varchar(50),upload_date varchar(50));
CREATE TABLE IF NOT EXISTS `all_post`(postID int NOT NULL AUTO_INCREMENT,PRIMARY KEY(postID),post_content text(100000),post_owner varchar(800),date varchar(50),author_photo varchar(500),time varchar(500),time2 varchar(500),likecomment text(100000),fullname varchar(500),what varchar(500),src varchar(500),privacy varchar(100),post_key varchar(50),`only_me` varchar(50));
CREATE TABLE IF NOT EXISTS `newnotice`(noticeID int NOT NULL AUTO_INCREMENT,PRIMARY KEY(noticeID),notice_content text(2000),date varchar(50),by_who varchar(20),fullname varchar(500),dp varchar(500),post_id varchar(500),notice_owner varchar(50));
CREATE TABLE IF NOT EXISTS `readnotice`(noticeID int NOT NULL AUTO_INCREMENT,PRIMARY KEY(noticeID),notice_content text(2000),date varchar(50),by_who varchar(20),fullname varchar(500),dp varchar(500),post_id varchar(500),notice_owner varchar(50)); 
CREATE TABLE IF NOT EXISTS `loaded_followers`(followersID int NOT NULL AUTO_INCREMENT,PRIMARY KEY(followersID),me varchar(50),star_username varchar(50),fullname varchar(50),dp varchar(200));
CREATE TABLE IF NOT EXISTS `followers_and_stars`(followersID int NOT NULL AUTO_INCREMENT,PRIMARY KEY(followersID),followers_username varchar(200),followers_fullname varchar(200),followers_dp varchar(500),star_username varchar(500),date varchar(50),star_fullname varchar(300),star_dp varchar(500));
CREATE TABLE IF NOT EXISTS `distinct_users`(usersID int NOT NULL AUTO_INCREMENT,PRIMARY KEY(usersID),username varchar(200),role varchar(200));
CREATE TABLE IF NOT EXISTS `ttuf`(filesID int NOT NULL AUTO_INCREMENT,PRIMARY KEY(filesID),username varchar(200),time varchar(200),date varchar(200),src varchar(200),group_codename varchar(50));
CREATE TABLE IF NOT EXISTS `tst_qtn`(qtnID int NOT NULL AUTO_INCREMENT,PRIMARY KEY(qtnID),questions text(5000),qtn_optn_w text(1000),crt_optn_w varchar(100),crt_optn_a varchar(3),mrk varchar(4),time varchar(200),date varchar(200));
CREATE TABLE IF NOT EXISTS `client_server_client_crypt_com`(cscccID int NOT NULL AUTO_INCREMENT,PRIMARY KEY(cscccID),session varchar(50),pub_key_snder text(5000),pub_key_rvcer text(5000),pri_key_snder text(5000),pri_key_rcver text(5000),snder_username varchar(50),rcver_username varchar(50),msg_timestamp varchar(500),snder_png_msg varchar(20),rcver_png_msg varchar(20),msg_status varchar(20));

CREATE TABLE IF NOT EXISTS `group_id`(groupID int NOT NULL AUTO_INCREMENT,PRIMARY KEY(groupID),group_name varchar(500),group_codename varchar(50),group_description text(5000),group_admins varchar(200),group_privacy varchar(50),group_icon varchar(200),time varchar(50),time2 varchar(50),date varchar(50));
CREATE TABLE IF NOT EXISTS `group_members`(groupID int NOT NULL AUTO_INCREMENT,PRIMARY KEY(groupID),username varchar(50),fullname varchar(200),dp varchar(50),group_codename varchar(50),time varchar(50),time2 varchar(50),date varchar(50));
CREATE TABLE IF NOT EXISTS `group_all_post`(postID int NOT NULL AUTO_INCREMENT,PRIMARY KEY(postID),post_content text(100000),post_owner varchar(800),date varchar(50),author_photo varchar(500),time varchar(500),time2 varchar(500),likecomment text(100000),fullname varchar(500),what varchar(500),src varchar(500),post_key varchar(50),group_codename varchar(50));

