/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ayobot;

/**
 *
 * @author fitechbot
 */
public class WebTechForm extends javax.swing.JPanel 
{
    // Variables declaration - do not modify//GEN-BEGIN:variables
   
    
    public javax.swing.JButton loginButton;
    public javax.swing.JLabel logoLabel;
    public javax.swing.JLabel passwordLabel;
    public javax.swing.JTextField passwordTextField;
    public javax.swing.JCheckBox rememberLogin;
    public javax.swing.JPanel submitPanel;
    public javax.swing.JPanel txtFieldPanel;
    public javax.swing.JLabel usernameLabel;
    public javax.swing.JTextField usernameTextField;

    // End of variables declaration//GEN-END:variables
    /**
     * Creates new form WebTechForm
     */
    public WebTechForm() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    public void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        submitPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        txtFieldPanel = new javax.swing.JPanel();
        passwordLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        passwordTextField = new javax.swing.JTextField();
        rememberLogin = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(102, 102, 0));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LOGIN TOKENS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setPreferredSize(new java.awt.Dimension(900, 800));
        setLayout(new java.awt.GridBagLayout());

        submitPanel.setBackground(new java.awt.Color(102, 102, 0));
        submitPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        submitPanel.setToolTipText("Enter Your Username an Password in The Text Fields Below");

        logoLabel.setBackground(new java.awt.Color(240, 19, 239));
        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setIcon(new javax.swing.ImageIcon("C:\\xampp\\htdocs\\fitechbot\\webtechApps\\webtech\\sefaslogo2.jpg"));

        txtFieldPanel.setBackground(new java.awt.Color(102, 102, 0));
        txtFieldPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        passwordLabel.setText("Password");

        usernameLabel.setText("Username");

        usernameTextField.setBackground(new java.awt.Color(224, 224, 224));
        usernameTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        usernameTextField.setText("Username");

        loginButton.setText("Login");

        passwordTextField.setBackground(new java.awt.Color(237, 237, 237));
        passwordTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordTextField.setText("Password");
        rememberLogin.setText("keep me logged in");
       

        javax.swing.GroupLayout txtFieldPanelLayout = new javax.swing.GroupLayout(txtFieldPanel);
        txtFieldPanel.setLayout(txtFieldPanelLayout);
        txtFieldPanelLayout.setHorizontalGroup(
            txtFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtFieldPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(txtFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txtFieldPanelLayout.createSequentialGroup()
                        .addComponent(usernameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usernameTextField))
                    .addGroup(txtFieldPanelLayout.createSequentialGroup()
                        .addComponent(passwordLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(txtFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(txtFieldPanelLayout.createSequentialGroup()
                                .addComponent(rememberLogin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 449, Short.MAX_VALUE)
                                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(passwordTextField))))
                .addContainerGap())
        );
        txtFieldPanelLayout.setVerticalGroup(
            txtFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtFieldPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(txtFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLabel))
                .addGap(26, 26, 26)
                .addGroup(txtFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel))
                .addGap(27, 27, 27)
                .addGroup(txtFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton)
                    .addComponent(rememberLogin))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout submitPanelLayout = new javax.swing.GroupLayout(submitPanel);
        submitPanel.setLayout(submitPanelLayout);
        submitPanelLayout.setHorizontalGroup(
            submitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(submitPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(submitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(submitPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(txtFieldPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        submitPanelLayout.setVerticalGroup(
            submitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(submitPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFieldPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 134;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(130, 48, 89, 46);
        add(submitPanel, gridBagConstraints);
        
       
        
    }// </editor-fold>//GEN-END:initComponents
    

    
    

    
}
